# Generated by Django 4.2.9 on 2026-01-29 03:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="valor",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="descrição"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("alimentacao", "Alimentação"),
                            ("transporte", "Transporte"),
                            ("moradia", "Moradia"),
                            ("saude", "Saúde"),
                            ("lazer", "Lazer"),
                            ("educacao", "Educação"),
                            ("salario", "Salário"),
                            ("investimentos", "Investimentos"),
                            ("outros", "Outros"),
                        ],
                        max_length=50,
                        verbose_name="categoria",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("receita", "Receita"), ("despesa", "Despesa")],
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                ("date", models.DateField(verbose_name="data")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "transação",
                "verbose_name_plural": "transações",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
